[auth]
jwt_algorithm = "HS256"
dev_mode = false  # Disabled to enable real Auth0 authentication
dev_entity_id = "10000000-0000-0000-0000-000000000001"  # Default dev user ID (must be UUID)
dev_entity_type = "developer"  # Default dev entity type
dev_permissions = ["read", "write", "admin"]  # Default dev permissions 